# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 11:52
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import mypartners.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonEmailDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_on', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text=b"Contact's full name", max_length=255, verbose_name=b'Full Name')),
                ('email', models.EmailField(blank=True, help_text=b"Contact's email address", max_length=255, verbose_name=b'Email')),
                ('phone', models.CharField(blank=True, default=b'', help_text=b'ie (123) 456-7890', max_length=30, verbose_name=b'Phone')),
                ('notes', models.TextField(blank=True, default=b'', help_text=b'Any additional information you want to record', max_length=1000, verbose_name=b'Notes')),
                ('last_action_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='ContactLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_flag', models.PositiveSmallIntegerField(verbose_name=b'action flag')),
                ('action_time', models.DateTimeField(auto_now=True, verbose_name=b'action time')),
                ('change_message', models.TextField(blank=True, verbose_name=b'change message')),
                ('contact_identifier', models.CharField(max_length=255)),
                ('delta', models.TextField(blank=True)),
                ('object_id', models.TextField(blank=True, null=True, verbose_name=b'object id')),
                ('object_repr', models.CharField(max_length=200, verbose_name=b'object repr')),
                ('successful', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ContactRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('contact_type', models.CharField(choices=[(b'email', b'Email'), (b'phone', b'Phone'), (b'meetingorevent', b'Meeting or Event'), (b'job', b'Job Followup'), (b'pssemail', b'Partner Saved Search Email')], max_length=50, verbose_name=b'Communication Type')),
                ('contact_email', models.CharField(blank=True, max_length=255, verbose_name=b'Contact Email')),
                ('contact_phone', models.CharField(blank=True, default=b'', max_length=30, verbose_name=b'Contact Phone Number')),
                ('location', models.CharField(blank=True, default=b'', max_length=255, verbose_name=b'Meeting Location')),
                ('length', models.TimeField(blank=True, null=True, verbose_name=b'Meeting Length')),
                ('subject', models.CharField(blank=True, default=b'', max_length=255, verbose_name=b'Subject or Topic')),
                ('date_time', models.DateTimeField(verbose_name=b'Date & Time')),
                ('notes', models.TextField(blank=True, default=b'', max_length=1000, verbose_name=b'Details, Notes or Transcripts')),
                ('job_id', models.CharField(blank=True, default=b'', max_length=40, verbose_name=b'Job Number/ID')),
                ('job_applications', models.CharField(blank=True, default=b'', max_length=6, verbose_name=b'Number of Applications')),
                ('job_interviews', models.CharField(blank=True, default=b'', max_length=6, verbose_name=b'Number of Interviews')),
                ('job_hires', models.CharField(blank=True, default=b'', max_length=6, verbose_name=b'Number of Hires')),
                ('last_action_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_one', models.CharField(blank=True, help_text=b'ie 123 Main St', max_length=255, verbose_name=b'Address Line One')),
                ('address_line_two', models.CharField(blank=True, help_text=b'ie Suite 100', max_length=255, verbose_name=b'Address Line Two')),
                ('city', models.CharField(help_text=b'ie Chicago, Washington, Dayton', max_length=255, verbose_name=b'City')),
                ('state', models.CharField(help_text=b'ie NY, WA, DC', max_length=200, verbose_name=b'State/Region')),
                ('country_code', models.CharField(default=b'USA', max_length=3, verbose_name=b'Country')),
                ('postal_code', models.CharField(blank=True, help_text=b'ie 90210, 12345-7890', max_length=12, verbose_name=b'Postal Code')),
                ('label', models.CharField(blank=True, help_text=b'ie Main Office, Corporate, Regional', max_length=60, verbose_name=b'Address Name')),
            ],
        ),
        migrations.CreateModel(
            name='OutreachEmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text=b'Email to send outreach efforts to.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile('(^[-!#$%&\'*+/=?^_`{}|~0-9A-Z]+(\\.[-!#$%&\'*+/=?^_`{}|~0-9A-Z]+)*\\Z|^"([\\001-\\010\\013\\014\\016-\\037!#-\\[\\]-\\177]|\\\\[\\001-\\011\\013\\014\\016-\\177])*"\\Z)', 2), b'Enter a valid email username.')], verbose_name=b'Email')),
            ],
        ),
        migrations.CreateModel(
            name='OutreachEmailDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['company', 'domain'],
            },
        ),
        migrations.CreateModel(
            name='OutreachRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('from_email', models.EmailField(help_text=b'Email outreach effort sent from.', max_length=255, verbose_name=b'Email')),
                ('to_emails', models.TextField(blank=True, verbose_name=b'To')),
                ('cc_emails', models.TextField(blank=True, verbose_name=b'CC')),
                ('email_body', models.TextField()),
                ('subject', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OutreachWorkflowState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_on', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text=b'Name of the Organization', max_length=255, verbose_name=b'Partner Organization')),
                ('data_source', models.CharField(blank=True, help_text=b'Website, event, or other source where you found the partner', max_length=255, verbose_name=b'Source')),
                ('uri', models.URLField(blank=True, help_text=b'Full url. ie http://partnerorganization.org', verbose_name=b'URL')),
                ('last_action_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(default=b'Employment Referral Resource Directory', max_length=255)),
                ('name', models.CharField(max_length=255, verbose_name=b'Partner Organization')),
                ('uri', models.URLField(blank=True)),
                ('region', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('area', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('phone_ext', models.CharField(blank=True, max_length=10)),
                ('alt_phone', models.CharField(blank=True, max_length=30)),
                ('fax', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('street1', models.CharField(blank=True, max_length=255)),
                ('street2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('st', models.CharField(blank=True, max_length=10)),
                ('zip_code', models.CharField(blank=True, max_length=12)),
                ('is_minority', models.BooleanField(default=False, verbose_name=b'minority')),
                ('is_female', models.BooleanField(default=False, verbose_name=b'female')),
                ('is_disabled', models.BooleanField(default=False, verbose_name=b'disabled')),
                ('is_veteran', models.BooleanField(default=False, verbose_name=b'veteran')),
                ('is_disabled_veteran', models.BooleanField(default=False, verbose_name=b'disabled_veteran')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerLibrarySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('search_url', models.URLField(blank=True, help_text=b'The URL to the user-facing search page for this source.')),
                ('download_url', models.URLField(blank=True, help_text=b'The URL used to download this source.')),
                ('params', models.TextField(blank=True, help_text=b'POST data used when downloading this source, serialized as JSON.')),
            ],
        ),
        migrations.CreateModel(
            name='PRMAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, max_length=767, null=True, upload_to=mypartners.models.get_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, b'Unprocessed'), (1, b'Approved'), (2, b'Denied')], default=1, verbose_name=b'Status Code')),
                ('last_modified', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=b'Last Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hex_color', models.CharField(blank=True, default=b'd4d4d4', max_length=6)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tag',
            },
        ),
    ]
