# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCareer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Custom Military/Civilian Career Map',
                'verbose_name_plural': 'Custom Military/Civilian Career Maps',
            },
        ),
        migrations.CreateModel(
            name='Moc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('branch', models.CharField(max_length=11)),
                ('title', models.CharField(max_length=300)),
                ('title_slug', models.SlugField(max_length=300)),
            ],
            options={
                'ordering': ['branch', 'code'],
                'verbose_name': 'Military Occupational Code/Rating',
                'verbose_name_plural': 'Military Occupational Codes',
            },
        ),
        migrations.CreateModel(
            name='MocDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_value', models.CharField(max_length=255)),
                ('service_branch', models.CharField(choices=[('f', 'Air Force'), ('a', 'Army'), ('c', 'Coast Guard'), ('m', 'Marines'), ('n', 'Navy')], max_length=2)),
                ('military_description', models.CharField(max_length=255)),
                ('civilian_description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Onet',
            fields=[
                ('title', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Onet',
                'verbose_name_plural': 'Onets',
            },
        ),
        migrations.AlterUniqueTogether(
            name='onet',
            unique_together=set([('title', 'code')]),
        ),
        migrations.AddField(
            model_name='moc',
            name='moc_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='moc_coding.MocDetail'),
        ),
        migrations.AddField(
            model_name='moc',
            name='onets',
            field=models.ManyToManyField(to='moc_coding.Onet'),
        ),
        migrations.AddField(
            model_name='customcareer',
            name='moc',
            field=models.ForeignKey(help_text=b'Sorted by branch, then MOC, then MOC                             title.', on_delete=django.db.models.deletion.CASCADE, to='moc_coding.Moc', verbose_name=b'Military Occupational Code'),
        ),
        migrations.AddField(
            model_name='customcareer',
            name='onet',
            field=models.ForeignKey(help_text=b'Standard occupational classifications                              developed by the US Dept. of Labor.', on_delete=django.db.models.deletion.CASCADE, to='moc_coding.Onet', verbose_name=b'O*NET-SOC'),
        ),
        migrations.AlterUniqueTogether(
            name='moc',
            unique_together=set([('code', 'branch')]),
        ),
    ]
