# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myemails', '0001_initial'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.Company'),
        ),
        migrations.AddField(
            model_name='event',
            name='sites',
            field=models.ManyToManyField(to='seo.SeoSite'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myemails.Event'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='footer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_for', to='myemails.EmailSection'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_for', to='myemails.EmailSection'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seo.Company'),
        ),
        migrations.AddField(
            model_name='emailtask',
            name='event_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_type', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='emailtask',
            name='object_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_model', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='emailsection',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seo.Company'),
        ),
    ]
