# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 18:34
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):

    AppAccess = apps.get_model("myjobs", "AppAccess")
    Activity = apps.get_model("myjobs", "Activity")
    analytics, _ = AppAccess.objects.get_or_create(name="Analytics")
    Activity.objects.get_or_create(
        name="view analytics",
        description="Access Analytics Graphs and Reporting.",
        app_access=analytics
    )

def backwards(apps, schema_editor):
    AppAccess = apps.get_model("myjobs", "AppAccess")
    Activity = apps.get_model("myjobs", "Activity")
    analytics = AppAccess.objects.get(name="Analytics")
    Activity.objects.filter(app_access=analytics).delete()
    analytics.delete()


class Migration(migrations.Migration):


    dependencies = [
        ("myjobs", "0002_auto_20161021_0752")
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
