# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50)),
                ('column_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100)),
                ('column_name', models.CharField(default=b'', max_length=50)),
                ('output_format', models.CharField(default=b'', max_length=50)),
                ('filter_interface_type', models.CharField(max_length=50, null=True)),
                ('filter_interface_display', models.CharField(max_length=50, null=True)),
                ('has_help', models.BooleanField(default=False)),
                ('alias', models.CharField(max_length=100)),
                ('multi_value_expansion', models.PositiveSmallIntegerField()),
                ('filter_only', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, default=b'', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('filters', models.TextField(default=b'{}')),
                ('results', models.FileField(upload_to=b'reports')),
            ],
        ),
        migrations.CreateModel(
            name='PresentationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('order_by', models.CharField(blank=True, default=b'', max_length=50)),
                ('app', models.CharField(default=b'mypartners', max_length=50)),
                ('model', models.CharField(default=b'contactrecord', max_length=50)),
                ('values', models.CharField(default=b'[]', max_length=500)),
                ('filters', models.TextField(default=b'{}')),
                ('results', models.FileField(upload_to=b'reports')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingTypeReportTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReportPresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('presentation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myreports.PresentationType')),
            ],
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('datasource', models.CharField(default=b'', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTypeDataTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myreports.Configuration')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myreports.DataType')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myreports.ReportType')),
            ],
        ),
        migrations.CreateModel(
            name='UserReportingTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('reporting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myreports.ReportingType')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('reporting_types', models.ManyToManyField(through='myreports.UserReportingTypes', to='myreports.ReportingType')),
            ],
        ),
        migrations.AddField(
            model_name='userreportingtypes',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myreports.UserType'),
        ),
        migrations.AddField(
            model_name='reporttype',
            name='data_types',
            field=models.ManyToManyField(through='myreports.ReportTypeDataTypes', to='myreports.DataType'),
        ),
        migrations.AddField(
            model_name='reportpresentation',
            name='report_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myreports.ReportTypeDataTypes'),
        ),
        migrations.AddField(
            model_name='reportingtypereporttypes',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myreports.ReportType'),
        ),
        migrations.AddField(
            model_name='reportingtypereporttypes',
            name='reporting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myreports.ReportingType'),
        ),
        migrations.AddField(
            model_name='reportingtype',
            name='report_types',
            field=models.ManyToManyField(through='myreports.ReportingTypeReportTypes', to='myreports.ReportType'),
        ),
    ]
