# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysearches', '0002_auto_20161021_0752'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('myjobs', '0001_initial'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondpartyaccessrequest',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.SeoSite'),
        ),
        migrations.AddField(
            model_name='role',
            name='activities',
            field=models.ManyToManyField(to='myjobs.Activity'),
        ),
        migrations.AddField(
            model_name='role',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.Company'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='send_log',
            field=models.ForeignKey(blank=True, help_text=b'Entries prior to the\n                                 release of saved search logging will\n                                 have no categories, meaning we cannot\n                                 match them with a SendGrid\n                                 response.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sendgrid_response', to='mysearches.SavedSearchLog'),
        ),
        migrations.AddField(
            model_name='companyaccessrequest',
            name='authorized_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorized_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyaccessrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='app_access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myjobs.AppAccess'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='myjobs.Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set([('ticket', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([('company', 'name')]),
        ),
    ]
