# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mymessages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name=b'Subject')),
                ('message_type', models.CharField(choices=[(b'error', b'Error'), (b'info', b'Info'), (b'block', b'Notice'), (b'success', b'Success')], max_length=200, verbose_name=b'Message type')),
                ('body', models.TextField(verbose_name=b'Body')),
                ('start_on', models.DateTimeField(default=mymessages.models.start_default, verbose_name=b'Start on')),
                ('expire_at', models.DateTimeField(db_index=True, default=mymessages.models.expire_default, help_text=b'Default is two weeks after message is sent.', null=True, verbose_name=b'Expire at')),
                ('btn_text', models.CharField(default=b'OK', max_length=100, verbose_name=b'Button text')),
                ('system', models.BooleanField(default=False, help_text=b'This is a system message and appears as an alert as well as in the inbox.', verbose_name=b'System message')),
                ('group', models.ManyToManyField(to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='MessageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(null=True, verbose_name=b'read at')),
                ('expired', models.BooleanField(db_index=True, default=False)),
                ('expired_on', models.DateTimeField(null=True, verbose_name=b'expired on')),
                ('deleted_on', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name=b'deleted on')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymessages.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='users',
            field=models.ManyToManyField(through='mymessages.MessageInfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='messageinfo',
            unique_together=set([('user', 'message')]),
        ),
    ]
