import re
address_line_1_terms = ['Alley','Aly',
                        'Arcade','Arc',
                        'Avenue','Ave',
                        'Beach','Bch',
                        'Bend','Bnd',
                        'Bottom','Btm',
                        'Boulevard','Blvd',
                        'Branch','Br',
                        'Bypass','Byp',
                        'Camp','Cp',
                        'Causeway','Cswy',
                        'Center','Ctr',
                        'Circle','Cir',
                        'Court','Ct',
                        'Cove','Cv',
                        'Creek','Crk',
                        'Crossing','Xing',
                        'Crossroad','Xrd',
                        'Drive','Dr',
                        'East','E',
                        'Expressway','Expy',
                        'Field','Fld',
                        'Freeway','Fwy',
                        'Front','Frnt',
                        'Gateway','Gtwy',
                        'Harbor','Hbr',
                        'Heights','Hts',
                        'Highway','Hwy',
                        'Island','Is',
                        'Junction','Jct',
                        'Lake','Lk',
                        'Lane','Ln',
                        'Mount','Mt',
                        'NE','Northeast',
                        'North','N',
                        'NW','Northwest',
                        'Parkway','Pky',
                        'Place','Pl',
                        'Plain','Pln',
                        'Plaza','Plz',
                        'Point','Pt',
                        'Ranch','Rnch',
                        'Rapids','Rpds',
                        'Ridge','Rdg',
                        'Road','Rd',
                        'Route','Rte',
                        'SE','Southeast',
                        'Skyway','Skwy',
                        'South','S',
                        'Space','Spc',
                        'Spring','Spg',
                        'Square','Sq',
                        'Station','Sta',
                        'Stravenue','Stra',
                        'Street','St',
                        'Summit','Smt',
                        'SW','Southwest',
                        'Terrace','Ter',
                        'Trace','Trce',
                        'Turnpike','Tpk',
                        'Valley','Vly',
                        'View','Vw',
                        'Village','Vlg',
                        'Well','Wl',
                        'West','W',
                        'Apartment','Apt',
                        'Building','Bldg',
                        'Office','Ofc',
                        'Room','Rm',
                        'Suite','Ste',
                        'Trailer','Trlr',
                        'Lobby','Lbby',
                        'Hangar','Hngr',
                        'Floor','Fl',
                        'Basement','Bsmt',
                        'PO','P.O.']

re_beginning_number = re.compile("^(d+)(.*)")

def identify_address(input_string):
    address_score = 0
    input_string = input_string.strip()
    match = re_beginning_number.match(input_string)
    if match:
        address_score += 10

    