# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 11:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mypartners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=60, verbose_name='Search Name')),
                ('url', models.URLField(max_length=300, verbose_name='URL of Search Results')),
                ('sort_by', models.CharField(choices=[(b'Relevance', 'Relevance'), (b'Date', 'Date')], default=b'Relevance', max_length=9, verbose_name='Sort by')),
                ('feed', models.URLField(max_length=300)),
                ('is_active', models.BooleanField(default=True, verbose_name='Search is Active')),
                ('email', models.EmailField(max_length=255, verbose_name='Which Email Address')),
                ('frequency', models.CharField(choices=[(b'D', 'Daily'), (b'W', 'Weekly'), (b'M', 'Monthly')], default=b'W', max_length=2, verbose_name='Frequency')),
                ('day_of_month', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], null=True, verbose_name='on')),
                ('day_of_week', models.CharField(blank=True, choices=[(b'1', 'Monday'), (b'2', 'Tuesday'), (b'3', 'Wednesday'), (b'4', 'Thursday'), (b'5', 'Friday'), (b'6', 'Saturday'), (b'7', 'Sunday')], max_length=2, null=True, verbose_name='on')),
                ('jobs_per_email', models.PositiveSmallIntegerField(choices=[(5, 5), (10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)], default=5, verbose_name='Jobs per Email')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('last_sent', models.DateTimeField(blank=True, editable=False, null=True)),
                ('custom_message', models.TextField(blank=True, max_length=300, null=True)),
                ('text_only', models.BooleanField(default=False, verbose_name='Send as a plain text email')),
            ],
            options={
                'verbose_name_plural': 'saved searches',
            },
        ),
        migrations.CreateModel(
            name='SavedSearchDigest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=255)),
                ('frequency', models.CharField(choices=[(b'D', 'Daily'), (b'W', 'Weekly'), (b'M', 'Monthly')], default=b'D', max_length=2, verbose_name='How often:')),
                ('day_of_month', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], null=True, verbose_name='on')),
                ('day_of_week', models.CharField(blank=True, choices=[(b'1', 'Monday'), (b'2', 'Tuesday'), (b'3', 'Wednesday'), (b'4', 'Thursday'), (b'5', 'Friday'), (b'6', 'Saturday'), (b'7', 'Sunday')], max_length=2, null=True, verbose_name='on')),
                ('send_if_none', models.BooleanField(default=False, editable=False, verbose_name='Send even if there are no results')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedSearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_sent', models.BooleanField()),
                ('was_received', models.BooleanField(default=False, help_text=b'If date_sent is very recent and was_received is unchecked, SendGrid may not have responded yet - give it a few minutes.')),
                ('reason', models.TextField()),
                ('recipient_email', models.EmailField(max_length=255)),
                ('new_jobs', models.IntegerField()),
                ('backfill_jobs', models.IntegerField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(db_index=True, max_length=32)),
                ('contact_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mypartners.ContactRecord')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerSavedSearch',
            fields=[
                ('savedsearch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysearches.SavedSearch')),
                ('url_extras', models.CharField(blank=True, help_text=b'Anything you put here will be added as query string parameters to each of links in the saved search.', max_length=255)),
                ('partner_message', models.TextField(blank=True, help_text=b'Use this field to provide a customized greeting that will be sent with each copy of this saved search.')),
                ('unsubscribed', models.BooleanField(default=False)),
                ('unsubscriber', models.EmailField(blank=True, editable=False, max_length=255, verbose_name=b'Unsubscriber')),
                ('last_action_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypartners.Partner')),
            ],
            bases=('mysearches.savedsearch',),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
