# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysearches', '0001_initial'),
        ('mypartners', '0001_initial'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersavedsearch',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.Company'),
        ),
        migrations.AddField(
            model_name='partnersavedsearch',
            name='tags',
            field=models.ManyToManyField(null=True, to='mypartners.Tag'),
        ),
    ]
