import React from 'react';
import { Component } from 'react';
import {connect} from 'react-redux';

import SideBarList from './SideBarList';

class SideBar extends Component{
  constructor(props, context) {
    super(props, context);
  }
  render(){
    const {sidebar} = this.props;
    return(
      <div>
        <div id='wrapper' className='active'>
          <div id='menu'>
            <SideBarList dimension={sidebar}/>
          </div>
          <div id='page-content'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tincidunt est eros, non gravida odio tristique et. Nam dictum ut neque varius finibus. Integer ac tortor posuere lacus ultricies interdum. Proin faucibus tristique urna, nec porta justo tristique non. Integer in porttitor ante. Aliquam non bibendum purus. Proin eu tempus est, eu imperdiet justo. Sed a odio at enim dignissim fringilla ut in justo. Mauris gravida nisl urna, id finibus nulla elementum et. Donec faucibus hendrerit tellus, eu consectetur enim cursus sit amet. Integer eros nunc, eleifend ut dapibus sit amet, suscipit quis dui. Praesent id egestas ligula. Sed quis lorem et nibh ultricies efficitur.

            Phasellus luctus tincidunt nisl a fringilla. Vivamus aliquet tortor non tristique mattis. Cras commodo tincidunt dui. Etiam ut semper turpis, non luctus turpis. Mauris dignissim, sem ut mollis facilisis, eros turpis elementum ipsum, non ultricies lorem purus id velit. Pellentesque vel ultrices augue. Nunc fringilla elit odio, et tempor elit semper a. Donec convallis nunc quis enim convallis tempor. Curabitur mi lectus, ornare nec elit sit amet, sodales finibus lacus. Phasellus vel lectus nec lectus pretium iaculis. Etiam efficitur erat fermentum, ultricies erat iaculis, vehicula nibh. Sed dignissim urna at ultricies dapibus.

            Fusce tristique mauris enim, at sollicitudin metus efficitur vel. In iaculis, ex in maximus laoreet, mi nibh consectetur tortor, quis dignissim nunc nisl ac turpis. Integer sed lorem bibendum, iaculis magna eget, posuere est. Donec consequat urna ut arcu condimentum, sed volutpat ligula auctor. Vestibulum vel pretium nisi. Fusce blandit velit dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed luctus aliquam volutpat. Nullam vulputate risus et enim dapibus, eu pretium lacus hendrerit. Mauris sodales bibendum tortor, nec mollis nulla posuere et.

            Sed sodales, nibh eget commodo sagittis, dui erat egestas ipsum, eu faucibus metus augue in metus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque suscipit aliquam mi, pretium volutpat lectus mattis quis. Fusce sed tellus eu ipsum eleifend congue a eu mauris. Proin mi erat, tincidunt nec nisl a, iaculis sodales neque. Ut mattis sodales commodo. Donec ac eros id tellus mollis consequat sit amet vitae dolor. Nam justo magna, varius non elementum consequat, blandit vel erat. Praesent rhoncus fringilla lorem, ut pulvinar ante efficitur et. Sed lobortis ut turpis ut cursus. Duis pellentesque ipsum sed justo dapibus, eget vulputate orci volutpat. Integer leo dui, cursus vel purus mollis, tincidunt dapibus eros. Curabitur viverra at neque vitae ullamcorper. Sed quis mattis risus.

            Pellentesque eget ullamcorper nisi. Donec auctor purus ultrices, consectetur ante eget, posuere ipsum. Donec vulputate suscipit augue ac varius. In placerat quam posuere, cursus tellus in, dictum ex. Pellentesque nulla augue, convallis sed dui nec, tincidunt ultrices risus. Morbi rhoncus elementum congue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris dignissim quis nibh eget tempus. Curabitur eros felis, tristique in egestas nec, viverra eu arcu. In semper ullamcorper nisl, at sodales quam. Fusce nisi nisl, commodo vel sapien a, pellentesque hendrerit lorem. Nulla consectetur facilisis leo in pharetra. Phasellus at dapibus metus. Nam gravida pulvinar enim. Sed nec viverra augue, id interdum est. Quisque lacinia dui egestas neque pellentesque pretium.

            Suspendisse potenti. Phasellus et mattis arcu. Nullam auctor est quis ex condimentum, non tristique libero rhoncus. Sed augue arcu, laoreet et ex eu, aliquet sollicitudin nibh. In vitae porta diam. Mauris maximus ante ut volutpat suscipit. Maecenas ut lectus est.

            Morbi porta eros eros, sed vestibulum purus tempor nec. Pellentesque rutrum in nibh ut ultricies. Etiam sed tincidunt ante, sed bibendum ipsum. Praesent mollis nisi eu suscipit laoreet. Sed at nunc augue. Duis ullamcorper elementum odio, non dapibus nibh sodales ac. Nullam at mauris ornare, condimentum sem non, finibus velit. Suspendisse vel sollicitudin libero. Phasellus consectetur enim ut purus luctus aliquet. Aenean vel metus metus. Ut at dui at turpis ultricies pellentesque.

            Morbi cursus porta feugiat. Aenean at molestie neque, a luctus massa. Quisque non sem tristique, interdum lectus eget, cursus enim. Donec at venenatis risus, nec ornare libero. Phasellus tempor, risus ac dapibus luctus, erat sem feugiat neque, in viverra nulla lacus in mi. Aenean tristique facilisis ultrices. Integer nec metus convallis, eleifend justo ac, lobortis purus. Proin suscipit, nisi ut ullamcorper dictum, ligula tortor consectetur enim, ut sagittis nulla ipsum nec sapien. Ut convallis purus eu mattis aliquet. Quisque a turpis quis mi accumsan ultrices. Ut in dignissim quam.

            Etiam non aliquam dolor. Cras eleifend gravida libero tempor ullamcorper. Cras dignissim in velit eget hendrerit. Sed iaculis pulvinar metus vel consectetur. Proin varius aliquam augue nec porttitor. Nulla luctus tortor eget mauris convallis malesuada at vitae nunc. Phasellus sollicitudin turpis leo, nec facilisis libero scelerisque in. Aenean lacinia nec odio at suscipit. Nulla quis hendrerit dolor, id pretium elit. Maecenas quis turpis eu massa aliquam rhoncus. Duis ornare quam fermentum, pretium leo ut, feugiat nisl. Curabitur posuere, ligula ut mollis dignissim, sem quam consectetur dolor, vel sodales magna est eget mi. Cras a egestas orci. Morbi eu aliquam metus, quis luctus lacus.

            Donec a lacus massa. Nulla ut erat lorem. Curabitur feugiat, quam tincidunt congue suscipit, massa massa mollis libero, volutpat fringilla leo erat id ipsum. Nunc tristique est ut ullamcorper posuere. Maecenas a iaculis turpis. Nullam posuere tincidunt dolor, ut rhoncus lacus rutrum a. Sed faucibus commodo massa quis vulputate. Nulla sollicitudin sit amet velit eget porttitor. Aenean efficitur mauris metus, in congue urna ullamcorper et. Sed iaculis luctus venenatis.

            Cras in enim justo. Phasellus eget convallis leo. Pellentesque finibus imperdiet pharetra. Pellentesque dictum elementum metus, eget pulvinar tortor porta a. Mauris maximus eget erat eu gravida. Sed elementum elementum vestibulum. Mauris ac massa vel nibh dictum varius. Pellentesque tincidunt venenatis magna vel faucibus. Donec quis mi fermentum, bibendum diam ut, hendrerit massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris quis hendrerit diam, id egestas nulla. Pellentesque ornare augue sit amet sodales dapibus. Pellentesque a tristique urna. Vivamus sed enim neque. Aliquam non eleifend nisl, sit amet congue nibh. Maecenas bibendum sem et lorem congue, varius sagittis dui tincidunt.

            Nunc bibendum justo purus, finibus elementum felis ultrices ut. Nam a ultricies mauris, sed accumsan sem. In id nisi id elit convallis consectetur quis quis velit. Maecenas venenatis neque nec dui porttitor efficitur. Praesent a magna ultrices, tristique elit vel, tincidunt neque. Sed semper faucibus diam at eleifend. In aliquet leo ligula, vel fermentum turpis faucibus at. Donec sed nisl metus. Nullam venenatis, leo et euismod sagittis, felis nulla pellentesque libero, quis lobortis justo metus malesuada dolor. Sed eget lorem placerat, ullamcorper nibh vitae, cursus lacus.

            In et erat non ante aliquet volutpat. In venenatis scelerisque mauris sed accumsan. Pellentesque posuere tellus erat, aliquet pellentesque purus convallis sit amet. Quisque in dui lacinia urna efficitur congue at luctus est. Nullam velit urna, pretium commodo blandit at, molestie sit amet nulla. Aenean dolor arcu, pharetra eu dui vel, bibendum tempor lectus. Proin sagittis commodo felis, a mattis ex tristique at. Nunc semper, risus a scelerisque vehicula, ipsum nulla lobortis dolor, nec fringilla tellus quam in metus. Fusce vel libero enim.

            Suspendisse id justo a sem consectetur facilisis sed varius orci. Aenean eget tortor justo. Suspendisse ac hendrerit arcu. Ut aliquet arcu nisl, ac dignissim leo placerat at. Integer condimentum rhoncus lorem, eget sodales orci suscipit non. Donec cursus nibh sit amet sem tincidunt tristique. Aenean pretium, turpis accumsan tempus suscipit, nisi leo dignissim orci, ac tincidunt enim felis nec mi. Mauris nec arcu diam. Donec eget sollicitudin sapien. Phasellus hendrerit mauris leo, eu rutrum enim blandit sed. Nam ultrices neque ut maximus egestas. Praesent ullamcorper faucibus libero et ultricies. Aenean eleifend ultricies risus, at vestibulum orci venenatis non. Donec tempus facilisis augue congue semper. Duis eu pulvinar elit.

            Aliquam tincidunt lobortis metus, vitae posuere erat blandit sed. Mauris sagittis mauris et turpis semper iaculis. Pellentesque eu augue eget ipsum faucibus porttitor. Nulla aliquet at libero ut imperdiet. Nulla accumsan eleifend ex nec bibendum. Pellentesque porttitor congue tortor ac vulputate. Vivamus tincidunt elementum hendrerit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus faucibus risus eu mattis laoreet. Praesent scelerisque eget nisl eget dictum. Cras hendrerit, risus ac scelerisque vestibulum, metus est consectetur turpis, a elementum eros arcu vitae dolor. Pellentesque vitae nisi eros.

            Nulla facilisi. Donec interdum vestibulum ligula, nec pellentesque quam semper id. Donec ultrices vestibulum suscipit. Cras vel eros vitae ex tincidunt tristique vel sit amet augue. Morbi risus metus, interdum non laoreet et, convallis at eros. Praesent congue odio eu posuere vulputate. Ut iaculis ex nec aliquet rutrum. Sed ut diam non velit pulvinar fermentum vel eu diam. In volutpat mollis pretium. Sed sit amet ligula eleifend, faucibus nisi et, cursus nibh. Ut vel ante maximus, porta diam et, iaculis dui. Fusce at orci eleifend, varius mauris vel, blandit sapien. Pellentesque ullamcorper vitae ante in faucibus. Vestibulum porta mollis facilisis.

            Nulla semper, enim sed volutpat tincidunt, orci tellus vehicula massa, ut tempus tellus nulla vel elit. Sed quam felis, commodo at iaculis ut, laoreet id erat. Nunc facilisis odio eu magna mattis mattis. Pellentesque vitae neque dictum, pretium elit vel, accumsan leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus lacinia faucibus lectus. Suspendisse interdum in leo eu luctus. Ut non luctus velit. Mauris et quam sed sapien egestas posuere. Maecenas volutpat dapibus turpis, at malesuada neque faucibus lacinia.

            Nullam tempus congue libero, scelerisque accumsan dui tincidunt in. Praesent velit est, gravida vitae dignissim sit amet, lobortis in nisi. Ut convallis venenatis mauris. Donec eu faucibus leo. Sed nec neque volutpat, ornare est ut, condimentum elit. Maecenas nec dapibus eros. Donec mollis aliquam orci ut dignissim. Nullam eu ante nisi.

            In condimentum malesuada risus quis consectetur. Aliquam erat volutpat. Vestibulum et ullamcorper diam. Vivamus vulputate vel neque eu vulputate. Duis ac quam tempus, vulputate est sit amet, bibendum nunc. Nullam interdum nisl eget orci pellentesque congue. Sed sit amet massa in orci tempus auctor. Nulla eu metus eu urna dictum consequat. Praesent eu libero commodo nisi sodales dapibus.

            Sed in laoreet nisi. Nulla feugiat mattis felis, in tempor nibh imperdiet vel. Suspendisse ut ultricies orci. Phasellus et convallis dolor, sed fringilla dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut porta sapien felis, sed luctus elit tincidunt consectetur. Vestibulum dictum, leo vel venenatis egestas, lacus arcu vulputate ligula, vitae accumsan enim erat a neque. Quisque efficitur maximus ipsum, non pellentesque ex hendrerit scelerisque. Maecenas varius enim vitae auctor ullamcorper. Integer euismod orci vehicula interdum convallis.

            Fusce non est ut massa facilisis dictum eget et nunc. Vivamus eros neque, luctus in consequat hendrerit, semper ac turpis. Nunc lacinia libero egestas lectus tincidunt lacinia. Nullam convallis urna sed tincidunt venenatis. Nullam et diam blandit, tempor augue quis, faucibus magna. Aenean viverra aliquam fermentum. Pellentesque magna ligula, mollis ac vehicula id, cursus a sapien. Pellentesque mattis nisl in risus tincidunt convallis. Vestibulum tempor augue quis consectetur dictum. Nulla nec arcu auctor, convallis justo eu, rutrum tortor. Nam nec nisl vel ex varius interdum. Maecenas dictum non erat vitae bibendum.

            Sed aliquam cursus lorem quis gravida. Fusce sit amet vestibulum lacus. Integer felis mauris, scelerisque ut pharetra et, rutrum vel ligula. Suspendisse potenti. Vivamus justo purus, maximus quis lorem in, volutpat eleifend turpis. Donec eu ex sit amet neque tristique luctus eu et metus. Mauris non tellus ut nisl accumsan rhoncus eu in magna. In in congue odio, eget egestas justo. Donec a ex nulla. Aliquam pretium ullamcorper nunc sit amet vehicula.

            Morbi lorem velit, sodales sed tellus ac, pretium cursus metus. Duis et malesuada erat, eu pulvinar elit. Mauris luctus scelerisque ligula, ut cursus arcu lobortis ut. Mauris placerat ante sagittis, rhoncus metus a, ornare lacus. Aliquam at rhoncus nisi, ac commodo urna. Vivamus fermentum nisl non dolor blandit, ut rutrum urna tincidunt. Quisque varius nulla ligula, id volutpat lectus vestibulum et. Integer in augue at neque hendrerit blandit. Vestibulum ornare nisl sit amet varius lobortis. Mauris sollicitudin pulvinar metus facilisis blandit. Aenean vehicula posuere tellus, nec tristique justo ornare eget. Nunc blandit metus ac leo cursus suscipit. Vivamus et convallis dui. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec non dolor ut tortor iaculis cursus ut a magna. Nunc blandit suscipit lacus, eget convallis turpis feugiat vitae.

            Etiam elementum sodales felis efficitur rhoncus. Nullam tempus sit amet justo nec tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut vestibulum diam vitae ante cursus, eu consequat metus varius. Sed fringilla risus et mi semper, ac laoreet ante pretium. Integer varius nunc sit amet lacus suscipit condimentum. Vestibulum congue elit eget sem elementum, nec ullamcorper libero vestibulum. Phasellus risus sem, pretium vel tristique quis, maximus a velit. Morbi semper sem quis augue ultrices, ac ornare velit finibus. Etiam sollicitudin porta sem.

            Aenean sed nibh eu urna porta sagittis elementum id odio. Vestibulum blandit vestibulum eleifend. Ut faucibus eleifend nisi ut luctus. Vivamus consectetur massa id accumsan facilisis. Integer nec lectus sagittis, efficitur felis non, rutrum enim. Nulla euismod elit velit, in elementum libero sagittis non. Etiam accumsan eu nibh vel elementum. Nulla sit amet nunc sed ex cursus suscipit at a ligula. Curabitur lectus nisi, maximus non dictum a, accumsan quis nulla. Fusce blandit rutrum dui, ut semper purus tristique non. In a eros ultricies, ornare arcu sed, cursus lectus. Vivamus id arcu erat. Nulla est metus, convallis sit amet arcu non, malesuada rhoncus neque.
          </div>
        </div>
      </div>
    );
  }
}

export default connect(state => ({
  sidebar: state.sidebarList
}))(SideBar);
