# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import social_links.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrositeCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name=b'Active')),
                ('include_all_sites', models.BooleanField(default=False, verbose_name=b"Include All Group's Sites")),
                ('display_rows', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], verbose_name=b'Display Rows')),
                ('carousel_title', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Carousel Title')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('link_sites', models.ManyToManyField(blank=True, null=True, related_name='linked_carousel', to='seo.SeoSite')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField()),
                ('link_title', models.CharField(db_index=True, max_length=60)),
                ('link_type', models.CharField(choices=[(b'company', b'Company'), (b'social', b'Social'), (b'directemployers', b'DirectEmployers')], max_length=255)),
                ('link_icon', models.CharField(default=b'default', max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('sites', models.ManyToManyField(to='seo.SeoSite')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=60, unique=True)),
                ('icon', models.FileField(max_length=767, upload_to=social_links.models.get_location)),
            ],
        ),
    ]
