# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('offset', models.PositiveIntegerField()),
                ('span', models.PositiveIntegerField()),
                ('template', models.TextField()),
                ('head', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ColumnBlockOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[(b'404', b'404'), (b'home_page', b'Home Page'), (b'job_detail', b'Job Detail Page'), (b'search_results', b'Job Search Results Page'), (b'login', b'Login Page'), (b'no_results', b'No Results Found')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[(b'staging', b'Staging'), (b'production', b'Production')], default=b'production', max_length=255)),
                ('head', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(blank=True, choices=[(b'', b'Inherit from Configuration'), (b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">', b'HTML 4.01 Transitional'), (b'<!DOCTYPE html>', b'HTML 5')], default=b'', max_length=255)),
                ('language_code', models.CharField(blank=True, choices=[(b'', b'Inherit from Configuration'), (b'zh', b'Chinese'), (b'da', b'Danish'), (b'en', b'English'), (b'fr', b'French'), (b'de', b'German'), (b'hi', b'Hindi'), (b'it', b'Italian'), (b'ja', b'Japanese'), (b'ko', b'Korean'), (b'pt', b'Portuguese'), (b'ru', b'Russian'), (b'es', b'Spanish')], default=b'', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RowOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblocks.Page')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblocks.Row')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ApplyLinkBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='BreadboxBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='ColumnBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='FacetBlurbBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='JobDetailBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='JobDetailBreadboxBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='JobDetailHeaderBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='LoginBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='MoreButtonBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='RegistrationBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='SavedSearchesListWidgetBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            options={
                'abstract': False,
            },
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='SavedSearchWidgetBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            options={
                'abstract': False,
            },
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='SearchBoxBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='SearchFilterBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='SearchResultBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='SearchResultHeaderBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='ShareBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='ToolsWidgetBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            options={
                'abstract': False,
            },
            bases=('myblocks.block',),
        ),
        migrations.CreateModel(
            name='VeteranSearchBox',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblocks.Block')),
            ],
            bases=('myblocks.block',),
        ),
        migrations.AddField(
            model_name='row',
            name='blocks',
            field=models.ManyToManyField(through='myblocks.BlockOrder', to='myblocks.Block'),
        ),
        migrations.AddField(
            model_name='page',
            name='rows',
            field=models.ManyToManyField(through='myblocks.RowOrder', to='myblocks.Row'),
        ),
    ]
