# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATSSourceCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buid', models.IntegerField(default=0)),
                ('ats_name', models.CharField(max_length=255)),
                ('parameter_name', models.CharField(max_length=255)),
                ('parameter_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CanonicalMicrosite',
            fields=[
                ('buid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('canonical_microsite_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyEmail',
            fields=[
                ('buid', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CustomExcludedViewSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buid', models.IntegerField(help_text='Business unit id that wants a custom exclusion')),
                ('view_source', models.IntegerField(help_text='View source that should be excluded')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationManipulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.IntegerField(help_text='Always 1 or 2')),
                ('buid', models.IntegerField(help_text='Business unit ID that owns this manipulation')),
                ('view_source', models.IntegerField(help_text='View source ID for aparticular manipulation')),
                ('action', models.CharField(blank=True, choices=[(b'sourcecodetag', b'sourcecodetag'), (b'amptoamp', b'amptoamp'), (b'cframe', b'cframe'), (b'anchorredirectissue', b'anchorredirectissue'), (b'urlswap', b'urlswap'), (b'replacethenadd', b'replacethenadd'), (b'replacethenaddpre', b'replacethenaddpre'), (b'sourceurlwrapappend', b'sourceurlwrapappend'), (b'sourcecodeinsertion', b'sourcecodeinsertion'), (b'sourceurlwrapunencoded', b'sourceurlwrapunencoded'), (b'sourceurlwrapunencodedappend', b'sourceurlwrapunencodedappend'), (b'switchlastinstance', b'switchlastinstance'), (b'switchlastthenadd', b'switchlastthenadd'), (b'sourcecodeswitch', b'sourcecodeswitch'), (b'doubleclickunwind', b'doubleclickunwind'), (b'fixurl', b'fixurl')], default=b'sourcecodetag', help_text='String describing what type of manipulation is to occur', max_length=255, null=True)),
                ('value_1', models.TextField(blank=True)),
                ('value_2', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailRedirectLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_addr', models.EmailField(max_length=254)),
                ('to_guid', models.CharField(max_length=38)),
                ('buid', models.IntegerField()),
                ('to_addr', models.EmailField(max_length=254)),
                ('sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExcludedViewSource',
            fields=[
                ('view_source', models.IntegerField(help_text='This view source will not redirect to a microsite', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('guid', models.CharField(db_index=True, help_text='42-character hex string', max_length=42, primary_key=True, serialize=False)),
                ('buid', models.IntegerField(default=0, help_text='Business unit ID for a given job provider')),
                ('uid', models.IntegerField(blank=True, help_text="Unique id on partner's ATS or other job repository", null=True, unique=True)),
                ('url', models.TextField(help_text='URL being manipulated')),
                ('new_date', models.DateTimeField(help_text='Date that this job was added')),
                ('expired_date', models.DateTimeField(blank=True, db_index=True, help_text='Date that this job was marked as expired', null=True)),
                ('job_location', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('company_name', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedirectAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buid', models.IntegerField(default=0)),
                ('action', models.IntegerField(choices=[(0, b'sourcecodetag'), (1, b'amptoamp'), (2, b'cframe'), (3, b'anchorredirectissue'), (4, b'urlswap'), (5, b'replacethenadd'), (6, b'replacethenaddpre'), (7, b'sourceurlwrapappend'), (8, b'sourcecodeinsertion'), (9, b'sourceurlwrapunencoded'), (10, b'sourceurlwrapunencodedappend'), (11, b'switchlastinstance'), (12, b'switchlastthenadd'), (13, b'sourcecodeswitch'), (14, b'doubleclickunwind'), (15, b'fixurl')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RedirectArchive',
            fields=[
                ('guid', models.CharField(db_index=True, help_text='42-character hex string', max_length=42, primary_key=True, serialize=False)),
                ('buid', models.IntegerField(default=0, help_text='Business unit ID for a given job provider')),
                ('uid', models.IntegerField(blank=True, help_text="Unique id on partner's ATS or other job repository", null=True, unique=True)),
                ('url', models.TextField(help_text='URL being manipulated')),
                ('new_date', models.DateTimeField(help_text='Date that this job was added')),
                ('expired_date', models.DateTimeField(blank=True, db_index=True, help_text='Date that this job was marked as expired', null=True)),
                ('job_location', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('company_name', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSource',
            fields=[
                ('view_source_id', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('friendly_name', models.CharField(blank=True, max_length=255)),
                ('microsite', models.BooleanField(default=False, help_text='Defunct; Use CanonicalMicrosite')),
                ('include_ga_params', models.BooleanField(default=False, help_text='Enables addition of Google Analytics parameters')),
                ('view_source_type', models.IntegerField(default=0)),
            ],
            options={
                'get_latest_by': 'view_source_id',
            },
        ),
        migrations.CreateModel(
            name='ViewSourceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of this view source group')),
                ('view_source', models.ManyToManyField(to='redirect.ViewSource')),
            ],
        ),
        migrations.AddField(
            model_name='redirectaction',
            name='view_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redirect.ViewSource'),
        ),
        migrations.AlterUniqueTogether(
            name='destinationmanipulation',
            unique_together=set([('action_type', 'buid', 'view_source')]),
        ),
        migrations.AlterUniqueTogether(
            name='customexcludedviewsource',
            unique_together=set([('buid', 'view_source')]),
        ),
        migrations.AlterIndexTogether(
            name='customexcludedviewsource',
            index_together=set([('buid', 'view_source')]),
        ),
        migrations.AddField(
            model_name='atssourcecode',
            name='view_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='redirect.ViewSource'),
        ),
        migrations.AlterUniqueTogether(
            name='redirectaction',
            unique_together=set([('buid', 'view_source', 'action')]),
        ),
        migrations.AlterIndexTogether(
            name='redirectaction',
            index_together=set([('buid', 'view_source')]),
        ),
        migrations.AlterUniqueTogether(
            name='atssourcecode',
            unique_together=set([('ats_name', 'parameter_name', 'parameter_value', 'buid', 'view_source')]),
        ),
    ]
