# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import seo.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_links', '0001_initial'),
        ('postajob', '0002_auto_20161021_0752'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('sites', '0002_alter_domain_unique'),
        ('myjobs', '0002_auto_20161021_0752'),
        ('taggit', '0002_auto_20150616_2121'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosite',
            name='microsite_carousel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_links.MicrositeCarousel'),
        ),
        migrations.AddField(
            model_name='seosite',
            name='parent_site',
            field=seo.models.NonChainedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_sites', to='seo.SeoSite'),
        ),
        migrations.AddField(
            model_name='seosite',
            name='site_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postajob.SitePackage'),
        ),
        migrations.AddField(
            model_name='seosite',
            name='site_tags',
            field=models.ManyToManyField(blank=True, null=True, to='seo.SiteTag'),
        ),
        migrations.AddField(
            model_name='seosite',
            name='special_commitments',
            field=models.ManyToManyField(blank=True, null=True, to='seo.SpecialCommitment'),
        ),
        migrations.AddField(
            model_name='seosite',
            name='view_sources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seo.ViewSource'),
        ),
        migrations.AddField(
            model_name='queryredirect',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='qparameter',
            name='redirect',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q', to='seo.QueryRedirect'),
        ),
        migrations.AddField(
            model_name='mocparameter',
            name='redirect',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moc', to='seo.QueryRedirect'),
        ),
        migrations.AddField(
            model_name='locationparameter',
            name='redirect',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='seo.QueryRedirect'),
        ),
        migrations.AddField(
            model_name='googleanalyticscampaign',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='googleanalytics',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='featuredcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.Company'),
        ),
        migrations.AddField(
            model_name='featuredcompany',
            name='seosite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.SeoSite'),
        ),
        migrations.AddField(
            model_name='custompage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='customfacet',
            name='business_units',
            field=models.ManyToManyField(blank=True, null=True, to='seo.BusinessUnit'),
        ),
        migrations.AddField(
            model_name='customfacet',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='customfacet',
            name='keyword',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.Company'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='group',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='app_access',
            field=models.ManyToManyField(blank=True, to='myjobs.AppAccess', verbose_name=b'App-Level Access'),
        ),
        migrations.AddField(
            model_name='company',
            name='job_source_ids',
            field=models.ManyToManyField(to='seo.BusinessUnit'),
        ),
        migrations.AddField(
            model_name='company',
            name='prm_saved_search_sites',
            field=models.ManyToManyField(blank=True, null=True, to='seo.SeoSite'),
        ),
        migrations.AddField(
            model_name='company',
            name='site_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='postajob.SitePackage'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='site_packages',
            field=models.ManyToManyField(blank=True, null=True, to='postajob.SitePackage'),
        ),
        migrations.AddField(
            model_name='billboardimage',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='billboardhotspot',
            name='billboard_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.BillboardImage'),
        ),
        migrations.AddField(
            model_name='atssourcecode',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='seositeredirect',
            unique_together=set([('redirect_url', 'seosite')]),
        ),
        migrations.AlterUniqueTogether(
            name='companyuser',
            unique_together=set([('user', 'company')]),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set([('name', 'user_created')]),
        ),
    ]
