# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postajob', '0001_initial'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.Company'),
        ),
        migrations.AddField(
            model_name='request',
            name='related_sites',
            field=models.ManyToManyField(null=True, to='seo.SeoSite'),
        ),
        migrations.AddField(
            model_name='purchasedproduct',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postajob.Invoice'),
        ),
        migrations.AddField(
            model_name='purchasedproduct',
            name='offline_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postajob.OfflinePurchase'),
        ),
        migrations.AddField(
            model_name='purchasedproduct',
            name='owner',
            field=models.ForeignKey(help_text=b'The company who will have access to this product.', on_delete=django.db.models.deletion.CASCADE, to='seo.Company'),
        ),
        migrations.AddField(
            model_name='purchasedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postajob.Product'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postajob.ProductGrouping'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postajob.Product'),
        ),
        migrations.AddField(
            model_name='productgrouping',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.Company'),
        ),
        migrations.AddField(
            model_name='productgrouping',
            name='products',
            field=models.ManyToManyField(help_text=b'The products you want displayed with this grouping.', null=True, through='postajob.ProductOrder', to='postajob.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.Company'),
        ),
        migrations.AddField(
            model_name='product',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postajob.Package'),
        ),
        migrations.AddField(
            model_name='package',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='offlinepurchase',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offlinepurchase',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postajob.Invoice'),
        ),
        migrations.AddField(
            model_name='offlinepurchase',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.Company'),
        ),
        migrations.AddField(
            model_name='offlinepurchase',
            name='products',
            field=models.ManyToManyField(through='postajob.OfflineProduct', to='postajob.Product'),
        ),
        migrations.AddField(
            model_name='offlinepurchase',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redeemed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offlineproduct',
            name='offline_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postajob.OfflinePurchase'),
        ),
        migrations.AddField(
            model_name='offlineproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postajob.Product'),
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='locations',
            field=models.ManyToManyField(related_name='jobs', to='postajob.JobLocation'),
        ),
        migrations.AddField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo.Company'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoiced_products',
            field=models.ManyToManyField(to='postajob.InvoiceProduct'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='seo.Company'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seo.Company'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='customer_of',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer', to='seo.Company'),
        ),
        migrations.AddField(
            model_name='sitepackage',
            name='owner',
            field=models.ForeignKey(blank=True, help_text=b'The owner of this site package. This should only be used if the site package will be used by the company for partner microsites.', null=True, on_delete=django.db.models.deletion.CASCADE, to='seo.Company'),
        ),
        migrations.AddField(
            model_name='sitepackage',
            name='sites',
            field=models.ManyToManyField(null=True, to='seo.SeoSite'),
        ),
        migrations.AddField(
            model_name='purchasedjob',
            name='purchased_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postajob.PurchasedProduct'),
        ),
        migrations.AlterUniqueTogether(
            name='productorder',
            unique_together=set([('product', 'group')]),
        ),
        migrations.AddField(
            model_name='job',
            name='site_packages',
            field=models.ManyToManyField(blank=True, null=True, to='postajob.SitePackage'),
        ),
    ]
